version: '3.7'
services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - firestore
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore:8081
  firestore:
    build:
      context: .
      dockerfile: Dockerfile-firestore
    ports:
      - "8081:8081"
